### ISSUE TITLE
Does this have to be a separate repository?

### ISSUE THREAD

**Issue by probonopd** [furybsd/furybsd-common-settings#1]
Does this have to be a separate repository?
Is it used by anything else than https://github.com/furybsd/furybsd-livecd?

If this was part of https://github.com/furybsd/furybsd-livecd, then forking that repository would allow one to play with the settings conveniently, and would make it much easier to send pull requests.

**Comment by probonopd** [comment]
If I understand it correctly, putting the contents from `/etc` into https://github.com/furybsd/furybsd-livecd/tree/master/overlays/uzip/etc would have the same effect?

**Comment by pkgdemon** [comment]
> If I understand it correctly, putting the contents from `/etc` into https://github.com/furybsd/furybsd-livecd/tree/master/overlays/uzip/etc would have the same effect?

In this case /usr/local/etc.

**Comment by pkgdemon** [comment]
> Does this have to be a separate repository?
> Is it used by anything else than https://github.com/furybsd/furybsd-livecd?
> 
> If this was part of https://github.com/furybsd/furybsd-livecd, then forking that repository would allow one to play with the settings conveniently, and would make it much easier to send pull requests.

Originally I had this installing via ports, and the ports were updated by furybsd-update.  I've since removed some of that.  It might make sense to merge this into furybsd-livecd soon.  I'll have to find a solution on what to do with furybsd-wallpapers, xfce-settings, etc.  I'm not really finished with the design at this point.  I need to think about it.

**Comment by pkgdemon** [comment]
If you want to raise a PR to move this specifically I am fine with that.  Otherwise I will try to get around to it in due time.  The applications like fury-wifi-tool I wanted to keep separate for now, and devise some other way of getting that installed, keeping it updated, etc.  Even xfce settings for example could need updated at some point, and I need to devise a way to get that update to the user because right now there isn't one...

**Comment by probonopd** [comment]
See my comments in https://github.com/furybsd/furybsd-livecd/issues/157#issuecomment-689371042. If these things need to be updated after the system has been installed to disk, then probably the clean way to do this is to have a pkg repository indeed?

**Comment by pkgdemon** [comment]
> See my comments in [furybsd/furybsd-livecd#157 (comment)](https://github.com/furybsd/furybsd-livecd/issues/157#issuecomment-689371042). If these things need to be updated after the system has been installed to disk, then probably the clean way to do this is to have a pkg repository indeed? (Still doesn't have to be a separate Git repository necessarily.)

It had to be separate to generate furybsd-common-settings, furybsd-xfce-settings, furybsd-kde-settings ports/packages easily.  For example without separation what would we need KDE settings for if we have XFCE?  See here for a list of what the different ports/packages were.  https://github.com/furybsd/furybsd-ports/tree/master/x11

**Comment by probonopd** [comment]
Please see https://github.com/furybsd/furybsd-livecd/issues/172 where I propose a solution for this.
